### ISSUE TITLE
Make it responsive (without any frameworks)

### ISSUE THREAD

**Issue by jeelpatel17** [jeelpatel17/paperpixel#1]
#### The preview link is in the repo description, see how it responses to mobile devices, so that you can get a clear understanding of what needs to be done.

**Comment by KevinMathewTh** [comment]
Hi , Can you assign me to this!

**Comment by KevinMathewTh** [comment]
Please guide me on how to recreate the bug.
In my Dev Tools it shows up okay .

also i was unable to direct to the preview link
![image](https://user-images.githubusercontent.com/44275582/95038641-3ff4fa00-06ec-11eb-96c8-101b0aad767d.png)

**Comment by jeelpatel17** [comment]
I meant the horizontal scrolling, the site shouldn't be scrolled horizontally, and still, content should look perfect. And as for the illustration, I'm struggling to set it at a proper distance from the heading (also not getting cropped). Btw, thanks for reviewing!

**Comment by adyasha9** [comment]
I want to help! I'll send you a PR

**Comment by jeelpatel17** [comment]
@KevinMathewTh Just send me PR, you can start working asap, without assigning.

**Comment by jeelpatel17** [comment]
@adyasha9 Go ahead!

**Comment by adyasha9** [comment]
@jeelpatel17  Please let me know if changes are up to your mark.

**Comment by jeelpatel17** [comment]
Thank you, its solved now! @adyasha9

**Comment by adyasha9** [comment]
@jeelpatel17  No problem
