### ISSUE TITLE
Body is  scroll in mobile(  x-axis )

### ISSUE THREAD

**Issue by mahendrarathore1742** [jeelpatel17/paperpixel#2]
The page  is scroll in  mobile  ( x-axis)

**Comment by jeelpatel17** [comment]
Yes, I know that, that's the issue. I want it to scroll only vertically (y-axis only)

**Comment by Shivangi-ch** [comment]
can i work on it?

**Comment by jeelpatel17** [comment]
@Shivangi-ch Yes, anyone can!
